import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Footer from '../components/footer/footer'
import Header from '../components/header/header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Real Vision Gaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'></link>
      </Head>

      <Header />
      <div className={styles.banner}>
          <img src="./banner12.jpg" alt="" />
          <div className={styles.bannerContent}>
            <span>Entrada Gratis</span>
            <span>Liga RVE Gratis</span>
            <span>Mobile/PC</span> 
          </div>

          <div className={styles.bannerDisplay}>
            <h2>Rainbow Six Tourbament</h2>
            <Link href=""><a>Leer mas</a></Link>
          </div>

      </div>
      <main>
        <section className={styles.section}>
        <h2>Comenzar es facil. Juego encendido</h2>
        <p>con Real Vision Gaming puedes ganar muchos premios mientras juegas, creas y compartes. </p>
        <div className={styles.cardContainer}>
          <div>
            <img src="./resume.png" alt="" />
            <p>Registrate y crea un perfil.</p>
            <p>Alocate. Relajate. Se tu.</p>
          </div>
          <div>
          <img src="./point.png" alt="" />
            <p>Suma puntos, es importante si quieres mas sorpresas</p>
          </div>
          <div>
          <img src="./community.png" alt="" />
            <p>Comparte con la comunidad y diviertete</p>
          </div>
          <div>
          <img src="./winning.png" alt="" />
            <p>Gana muchos precios haciendo lo que amas. Ve por la gloria.</p>
          </div>
        </div>
        </section>
        <section className={styles.section}>
          <h2>Plataforma mundial con cualidades exclusivas</h2>
          <p>Eres un streamer, un jugador profesional, un vlogger o una ama de casa?</p>
          <div className={styles.content}>
            <ul className={styles.platformList}>
              <li><span>01</span> <span><i className='bx bxs-arrow-to-right' ></i> Participar en torneos</span></li>
              <li><span>02</span> <span><i className='bx bxs-arrow-to-right' ></i> Crear transmisiones en vivo</span></li>
              <li><span>03</span> <span><i className='bx bxs-arrow-to-right' ></i> Subir videos cortos</span></li>
              <li><span>04</span> <span><i className='bx bxs-arrow-to-right' ></i> Chatear</span></li>
            </ul>
            <img src="./trofeorve.png" alt="" />
          </div>
        </section>
        <section className={styles.section}>
          <h2>Noticias</h2>
          <div className={styles.cardContainerNews}>
            <div className={styles.card}>
              <img src="./freefire.jpg" alt="" />
              <div>
                <span>Hace 5 dias</span>
                <p>Revolutionizing Mobile Gaming With A COnversation With Ex MAcAfee CTO Rosen Sharma</p>
                <Link href=""><a><i className='bx bxs-right-arrow'></i></a></Link>
              </div>
            </div>
            <div className={styles.card}>
            <img src="./freefire.jpg" alt="" />
              <div>
                <span>Hace 5 dias</span>
                <p>Revolutionizing Mobile Gaming With A COnversation With Ex MAcAfee CTO Rosen Sharma</p>
                <Link href=""><a><i className='bx bxs-right-arrow'></i></a></Link>
              </div>
            </div>
            <div className={styles.card}>
            <img src="./freefire.jpg" alt="" />
              
              <div>
                <span>Hace 5 dias</span>
                <p>Revolutionizing Mobile Gaming With A COnversation With Ex MAcAfee CTO Rosen Sharma</p>
                <Link href=""><a><i className='bx bxs-right-arrow'></i></a></Link>
              </div>
            </div>
          </div>
        </section>
        <section className={styles.section}>
          <h2>Quieres aclarar algunas dudas frecuentes?</h2>
          <div className={styles.detailsContainer}>

          <details>
            <summary>Que hace que esto sea diferente de otras plataformas similares?</summary>
            <p></p>
          </details>
          <details>
            <summary>Cuendo recibire el dinero ganado en mi cuenta?</summary>
            <p></p>
          </details>
          <details>
            <summary>Que analisis ofrecera en su panel de control?</summary>
            <p></p>
          </details>
          <details>
            <summary>Se venderan o utilizaran mis datos sin mi permiso?</summary>
            <p></p>
          </details>
          <details>
            <summary>Real Vision gaming se reserva el derecho de eliminar todo el contenido subido a su plataforma?</summary>
            <p></p>
          </details>
          </div>

        </section>
      </main>

      <Footer />
    </div>
  )
}
