import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import Footer from "../components/footer/footer";
import Header from "../components/header/header";
import styles from "../styles/Home.module.css";
import { format, register } from "timeago.js";

export default function Home({posts}) {

  register(
    "es_ES",
    (number, index, total_sec) =>
      [
        ["justo ahora", "ahora mismo"],
        ["hace %s segundos", "en %s segundos"],
        ["hace 1 minuto", "en 1 minuto"],
        ["hace %s minutos", "en %s minutos"],
        ["hace 1 hora", "en 1 hora"],
        ["hace %s horas", "in %s horas"],
        ["hace 1 dia", "en 1 dia"],
        ["hace %s dias", "en %s dias"],
        ["hace 1 semana", "en 1 semana"],
        ["hace %s semanas", "en %s semanas"],
        ["hace 1 mes", "en 1 mes"],
        ["hace %s meses", "en %s meses"],
        ["hace 1 año", "en 1 año"],
        ["hace %s años", "en %s años"],
      ][index]
  );

  const timeago = (timestamp) => format(timestamp, "es_ES");


  console.log(posts)
  return (
    <div className={styles.container}>
      <Head>
        <title>Real Vision Gaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
      </Head>

      <Header />
      <div className={styles.banner}>
        <img src="./vikings.jpg" alt="" />
        <div className={styles.bannerContent}>
          <span>Entrada Gratis</span>
          <span>Liga RVE Gratis</span>
          <span>Mobile/PC</span>
        </div>

        <div className={styles.bannerDisplay}>
          <h2>Rainbow Six Tourbament</h2>
          <Link href="">
            <a>Leer mas</a>
          </Link>
        </div>
      </div>
      <main>
        <section className={styles.section}>
          <h2>Comenzar es facil. Juego encendido</h2>
          <p>
            con Real Vision Gaming puedes ganar muchos premios mientras juegas,
            creas y compartes.{" "}
          </p>
          <div className={styles.cardContainer}>
            <div>
              <img src="./resume.png" alt="" />
              <p>Registrate y crea un perfil.</p>
              <p>Alocate. Relajate. Se tu.</p>
            </div>
            <div>
              <img src="./point.png" alt="" />
              <p>Suma puntos, es importante si quieres mas sorpresas</p>
            </div>
            <div>
              <img src="./community.png" alt="" />
              <p>Comparte con la comunidad y diviertete</p>
            </div>
            <div>
              <img src="./winning.png" alt="" />
              <p>Gana muchos precios haciendo lo que amas. Ve por la gloria.</p>
            </div>
          </div>
        </section>
        <section className={styles.section}>
          <h2>Plataforma mundial con cualidades exclusivas</h2>
          <p>
            Eres un streamer, un jugador profesional, un vlogger o una ama de
            casa?
          </p>
          <div className={styles.content}>
            <ul className={styles.platformList}>
              <li>
                <span>01</span>{" "}
                <span>
                  <i className="bx bxs-arrow-to-right"></i> Participar en
                  torneos
                </span>
              </li>
              <li>
                <span>02</span>{" "}
                <span>
                  <i className="bx bxs-arrow-to-right"></i> Crear transmisiones
                  en vivo
                </span>
              </li>
              <li>
                <span>03</span>{" "}
                <span>
                  <i className="bx bxs-arrow-to-right"></i> Subir videos cortos
                </span>
              </li>
              <li>
                <span>04</span>{" "}
                <span>
                  <i className="bx bxs-arrow-to-right"></i> Chatear
                </span>
              </li>
            </ul>
            <img src="./trofeorve.png" alt="" />
          </div>
        </section>
        <section className={styles.section}>
          <h2>Noticias</h2>
          <div className={styles.cardContainerNews}>
            {posts.filter((post, index) => post.category == 'Gaming' && index < 13)
            .map((post) => (
            <Link href={`blog/${post.slug}`} key={post.id}>
            <a className={styles.card}>
            <img src={post.image} alt={post.title} />
            <div>
              <span>{timeago(post.createdAt)}</span>
              <p>
                {post.title}
              </p>
              {/* <Link >
                <a>
                  <i className="bx bxs-right-arrow"></i>
                </a>
              </Link> */}
            </div>
            </a>
          </Link>
            ))}
          </div>
        </section>
        <section className={styles.section}>
          <h2>Quieres aclarar algunas dudas frecuentes?</h2>
          <div className={styles.detailsContainer}>
            <details>
              <summary>
                Que hace que esto sea diferente de otras plataformas similares?
              </summary>
              <p></p>
            </details>
            <details>
              <summary>Cuendo recibire el dinero ganado en mi cuenta?</summary>
              <p></p>
            </details>
            <details>
              <summary>Que analisis ofrecera en su panel de control?</summary>
              <p></p>
            </details>
            <details>
              <summary>
                Se venderan o utilizaran mis datos sin mi permiso?
              </summary>
              <p></p>
            </details>
            <details>
              <summary>
                Real Vision gaming se reserva el derecho de eliminar todo el
                contenido subido a su plataforma?
              </summary>
              <p></p>
            </details>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}

export async function getServerSideProps() {
  const client = new ApolloClient({
    uri: "https://rveapiql.herokuapp.com/graphql",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query {
        posts {
          id
          description
          createdAt
          category
          slug
          image
          title
        }
      }
    `,
  });

  return {
    props: {
      posts: data.posts,
    },
  };
}
